"""user, snowboard and snowboard_photo_link tables created

Revision ID: 09965a3b2be2
Revises: 
Create Date: 2022-08-16 19:40:24.151078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09965a3b2be2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('snowboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('ad_placement_date', sa.DateTime(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('ad_text', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('mongodb_id', sa.String(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name', 'price', 'ad_text', 'user_id')
    )
    op.create_index(op.f('ix_snowboard_ad_text'), 'snowboard', ['ad_text'], unique=False)
    op.create_index(op.f('ix_snowboard_price'), 'snowboard', ['price'], unique=False)
    op.create_index(op.f('ix_snowboard_product_name'), 'snowboard', ['product_name'], unique=False)
    op.create_index(op.f('ix_snowboard_user_id'), 'snowboard', ['user_id'], unique=False)
    op.create_table('snowboard_photo_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_link', sa.String(), nullable=True),
    sa.Column('snowboard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snowboard_id'], ['snowboard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_link')
    )
    op.create_index(op.f('ix_snowboard_photo_link_snowboard_id'), 'snowboard_photo_link', ['snowboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snowboard_photo_link_snowboard_id'), table_name='snowboard_photo_link')
    op.drop_table('snowboard_photo_link')
    op.drop_index(op.f('ix_snowboard_user_id'), table_name='snowboard')
    op.drop_index(op.f('ix_snowboard_product_name'), table_name='snowboard')
    op.drop_index(op.f('ix_snowboard_price'), table_name='snowboard')
    op.drop_index(op.f('ix_snowboard_ad_text'), table_name='snowboard')
    op.drop_table('snowboard')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
