"""snowboards and snowboard_photo_links tables

Revision ID: c98f69dab677
Revises: 
Create Date: 2022-06-24 14:15:07.037320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98f69dab677'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snowboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('ad_placement_date', sa.DateTime(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('ad_text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name', 'price', 'ad_text', 'user_id', 'url')
    )
    op.create_table('snowboard_photo_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_link', sa.String(), nullable=True),
    sa.Column('snowboard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snowboard_id'], ['snowboard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_link')
    )
    op.create_index(op.f('ix_snowboard_photo_link_snowboard_id'), 'snowboard_photo_link', ['snowboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snowboard_photo_link_snowboard_id'), table_name='snowboard_photo_link')
    op.drop_table('snowboard_photo_link')
    op.drop_table('snowboard')
    # ### end Alembic commands ###
